routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\GamesController;
use App\Http\Controllers\LevelsController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\PlayController;
use App\Http\Controllers\LogsController;
use App\Http\Controllers\PupilsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PublicController::class,'index'])->name('home');
Route::get('img/{filename}', [PublicController::class,'img'])->name('img');
Route::get('dashboard', [PlayController::class,'index'])->name('dashboard');
Route::get('level/{id}', [PlayController::class,'level'])->name('level');
Route::get('play/{level_id}/{id}', [PlayController::class,'play'])->name('play');
Route::get('score/{level_id}/{id}', [PlayController::class,'score'])->name('score');
Route::post('answer', [PlayController::class,'answer'])->name('answer');
Route::get('scores', [LogsController::class,'index'])->name('scores');
Route::post('login/pupil', [PublicController::class,'pupil_login'])->name('pupil_login');

Route::get('play', [PublicController::class,'play'])->name('start');

require __DIR__.'/auth.php';

// Restful Controllers
Route::resources([
    'users' => UsersController::class,
    'games' => GamesController::class,
    'levels' => LevelsController::class,
    'questions' => QuestionsController::class,
    'pupils' => PupilsController::class
]);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'points',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Validator;
use Hash;

class UsersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->validation = [
            'username' => 'required|string|max:255|unique:users',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed'
        ];
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $params['users'] = User::paginate(10);

        return view('admin.users.index',$params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Input validation
        $validator = Validator::make( $request->all(), $this->validation );

        if( $validator->fails() ) 
        {
            return redirect('users/create')->withInput($request->all())->with('error', $validator->messages());
        }

        $user = new User;
        $user->fill( $request->all() );
        // $user->pwd = $request->input('password');
        $user->password = Hash::make( $request->input('password') );   
        $user->save();

        return redirect('users')->with('success', 'Admin successfully registered.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $user = User::find($id);

        if (!$user) {
            return redirect('users')->with('error','Admin no longer exist.');        
        }
        
        $params['user'] = User::find($id);
        return view('admin.users.edit',$params);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $validation = $this->validation;

        // check if password is changed.
        if ( empty($request->input('password')) ) {
            unset($validation['password']);
        }

        if ($request->input('email')==$user->email) {
            $validation['email'] = 'required|email|max:255';
        }

        if ( $request->input('username')==$user->username ) {
            $validation['username'] = 'required|string|max:255';
        }

        // Input validation
        $validator = Validator::make( $request->all(), $validation );

        if( $validator->fails() ) 
        {
            return redirect('users/'.$id.'/edit')->with('error', $validator->messages());
        }

        $user->username = $request->input('username');
        // $user->first_name = $request->input('first_name');
        // $user->last_name = $request->input('last_name');
        // $user->middle_name = $request->input('middle_name');
        $user->email = $request->input('email');
        $user->role = 'admin';

        if ( !empty($request->input('password')) ) {
            $user->password = Hash::make($request->input('password'));   
            // $user->pwd = $request->input('password');
        }

        $user->save();

        return redirect('users/'.$id.'/edit')->with('success', 'Admin details successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $q = User::find($id);

        if (!$q) 
        {
            return redirect('users')->with('error','Admin no longer exists!');
        }

        $q->delete();

        return redirect('users')->with('success','Admin successfully removed.');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/users/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Register Admin') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    
                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <div class="card">
                        <div class="card-header">
                            Register Admin
                        </div>
                        <div class="card-body">
                            <form action="{{ route('users.store') }}" method="POST" role="form">
                                @csrf
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="exam-name">Username:</label>
                                            <input type="text" class="form-control" name="username" required>
                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label for="exam-email">Email:</label>
                                            <input type="email" class="form-control" name="email" required>
                                            @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="exam-password">Password:</label>
                                            <input type="password" class="form-control" name="password" required>
                                            @error('password')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label for="exam-password_confirmation">Repeat Password:</label>
                                            <input type="password" class="form-control" name="password_confirmation" required>
                                            @error('password_confirmation')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                
                                <hr>
                                <br>
                                <button type="submit" class="btn btn-primary">Register &nbsp;<i class="bi bi-save"></i></button>
                            </form>
                        </div>
                    </div>

                    

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/users/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Admin') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    
                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />
                    <x-auth-session-status class="mb-4" :status="session('success')" />
                    
                    <div class="card">
                        <div class="card-header">
                            Edit Admin
                        </div>
                        <div class="card-body">
                            <form action="{{ route('users.update', $user->id) }}" method="POST" role="form">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="exam-name">Username:</label>
                                            <input type="text" class="form-control" name="username" value="{{ $user->username }}" required>
                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label for="exam-email">Email:</label>
                                            <input type="email" class="form-control" name="email" value="{{ $user->email }}" required>
                                            @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="exam-password">Password:</label>
                                            <input type="password" class="form-control" name="password">
                                            @error('password')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label for="exam-password_confirmation">Repeat Password:</label>
                                            <input type="password" class="form-control" name="password_confirmation">
                                            @error('password_confirmation')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                
                                <hr>
                                <br>
                                <button type="submit" class="btn btn-primary">Save &nbsp;<i class="bi bi-save"></i></button>
                            </form>
                        </div>
                    </div>

                    

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Admins') }} <a href="{{ route('users.create') }}" class="btn btn-primary btn-sm float-right">Register Admin</a>
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    
                    <!-- Session Status -->
                    <x-auth-session-status class="mb-4" :status="session('success')" />

                    @if($users->count())
                        
                        <table class="table table-responsive table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Username</th>
                                    <th>Email</th>
                                    {{-- <th>Points</th> --}}
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach($users as $user)
                                    @if($user->role == 'admin')
                                    <tr>
                                        <td>{{ $user->username }}</td>
                                        <td>{{ $user->email }}</td>
                                        {{-- <td>{{ $user->points }}</td> --}}
                                        <td>
                                            <a href="#" onclick="removeItem({{$user->id}})" class="btn btn-sm btn-danger float-right">Remove <i class="bi bi-x-lg"></i></a>
                                            <a href="{{ route('users.edit',$user->id) }}" class="btn btn-sm btn-info float-right mr-4">Edit <i class="bi bi-pencil-square"></i></a>
                                            <form id="delete-{{$user->id}}" action="{{ route('users.destroy',$user->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </td>
                                    </tr>
                                    @endif
                                @endforeach
                            </tbody>
                        </table>

                        {{ $users->links() }}
                    @endif
                
                </div>
            </div>
        </div>
    </div>
    <script>
        function removeItem(id) {
            var txt;
            if (confirm("Are you sure?")) {
                jQuery('#delete-'+id).submit();
            }
        }
    </script>
</x-app-layout>